### ISSUE TITLE
[自荐]validate-spring-boot-starter 一个强大灵活简单的spring参数校验框架 

### ISSUE THREAD

**Issue by liangbaika** [juejin-im/open-source#10]
# 项目地址  https://github.com/liangbaika/validate
# 类型 java
# 项目描述
是一个validate-spring-boot-starter,与springboot框架无缝集成的灵活丰富的验证框架。 完全兼容javax-validation 和 hibernate Validation，并比他们更灵活 简单 强大 versus springboot Framework for seamless integration of verification framework.
#  优点
1.内置常用验证
2.对 javax validation 和hibernate-validate 完全兼容
3. 支持验证Bean可重用
4.支持条件分组 支持自定义验证器 （自定义更简单强大，可做到和业务完全解耦）
5.多条件操作符
6.聚合功能
7.错误信息提示更加友好 更准确
8.简单 灵活 无脑

**Comment by kkzhilu** [comment]
很好的项目，作为一个Javaer我都迫不及待想去试一下，不过可以继续完善，然后推广一下~
小Tips：可以在掘金发沸点或者撰写开源文章给自己的项目增加热度呀🤞

**Comment by liangbaika** [comment]
写过一些文章 没啥人访问 没啥热度  掘金能帮推下？哈哈------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Super-Kerwin&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月26日(星期三) 上午7:03
收件人:&nbsp;&quot;juejin-im/open-source&quot;<open-source@noreply.github.com&gt;;
抄送:&nbsp;&quot;凉白开&quot;<1144388620@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [juejin-im/open-source] [自荐]validate-spring-boot-starter 一个强大灵活简单的spring参数校验框架  (#10)
