### ISSUE TITLE
【自荐】简洁的人人影视客户端 Fultter版

### ISSUE THREAD

**Issue by Krosxx** [juejin-im/open-source#11]
## 项目地址

https://github.com/Vove7/yyets_flutter

## 项目简介

> 人人影视Flutter版 还你一个清净  

### 功能一览

- 支持全平台：Android, IOS, Windows, MAC OS, Web, Web Server.
- 安卓端边下边播
- 自动适应DarkMode
- 本地播放
- 我的收藏
- 影视搜索
- 用户登录

### 效果展示

**[Web端体验](http://vove.gitee.io/yyets_flutter_web_demo)**

<div><img src="/Vove7/yyets_flutter/raw/master/screenshots/s1.jpg" width="250">
  <img src="/Vove7/yyets_flutter/raw/master/screenshots/s2.jpg" width="250"></div>

<div><img src="/Vove7/yyets_flutter/raw/master/screenshots/s3.jpg" width="250">
  <img src="/Vove7/yyets_flutter/raw/master/screenshots/s4.jpg" width="250"></div>

<div><img src="/Vove7/yyets_flutter/raw/master/screenshots/s5.jpg" width="250">
  <img src="/Vove7/yyets_flutter/raw/master/screenshots/s6.jpg" width="250"></div>
<div><img src="/Vove7/yyets_flutter/raw/master/screenshots/s7.jpg" width="500"></div>

**Comment by kkzhilu** [comment]
非常有幸遇到一个Fultter大佬，暂时无法得到推荐，但是你可以继续完善，未来我们会考虑哦✌
