### ISSUE TITLE
【自荐】热点爬虫：EggCrawel

### ISSUE THREAD

**Issue by xiaojia21190** [juejin-im/open-source#12]
### 项目地址
[egg_crawel](https://github.com/xiaojia21190/egg_crawel)
[ZY_Player_flutter](https://github.com/xiaojia21190/ZY_Player_flutter)

### 项目简介
热搜爬虫（热搜，小说，漫画，微信公众号，影视，rss解析）

### 功能一览

1. 定时爬取热点网站的内容，存入mysql数据库
2. 采用了puppeteer作为爬取引擎，cherrio 作为网页解析的工具
3. 目前爬取网站的数量已经达到200多个

### 在线适用
[http://140.143.207.151:7001/hotSearch?search=%E9%BB%91%E8%8B%B9%E6%9E%9C](url) 热搜搜索

**Comment by kkzhilu** [comment]
抱歉哦，暂时不能收录至推荐中，你可以继续完善，以便在后续的实用 / 学习实践领域得到推荐~🤞

**Comment by kkzhilu** [comment]
暂时关闭
