### ISSUE TITLE
【自荐】力扣题解 (A Record of My Problem Solving Journey)

### ISSUE THREAD

**Issue by azl397985856** [juejin-im/open-source#15]
开源项目的介绍:leetcode 题解，记录自己的 leetcode 解题之路。
语言:JS，Python，CPP，Java
分类:算法
推荐理由: 各种算法套路，和市面上怎么做不同。 本仓库侧重系统性，善于挖掘题目背后的逻辑。
用途: 算法面试，个人提升
效果图:

![image](https://user-images.githubusercontent.com/12479470/91393851-ec7dc980-e86c-11ea-8ada-d3ef3b92b5c1.png)

![image](https://user-images.githubusercontent.com/12479470/91394042-f99ab880-e86c-11ea-8d40-5953e104be15.png)

重要的里程碑事件:
成就: 35k+ star，多次登上 github 热门，github leetcode 搜索排名第一

仓库地址：https://github.com/azl397985856/leetcode

**Comment by kkzhilu** [comment]
不考虑有明显引流倾向的项目哦，项目真的很棒！😛
