### ISSUE TITLE
【自荐】✨强大、优雅的小程序异步库🚀 小程序promise

### ISSUE THREAD

**Issue by zisheng-ai** [juejin-im/open-source#2]
## 项目推荐
- 项目地址：https://github.com/youngjuning/wx-promise-pro

- 类别：JS

- 项目后续更新计划：添加自定义方法

- 项目描述：
  - 支持 finnaly、typescript 的微信小程序异步解决方案

- 推荐理由:
  - 方便集成：一处引用，处处使用
  - 把微信小程序所有异步 API promise 化并挂在到wx.pro 对象下
  - 支持 ES2018 finally 特性
  - 支持 TypeScript 开发

- 示例代码：

```js
import { promisifyAll, promisify } from 'wx-promise-pro'
// promisify all wx‘s api
promisifyAll()
// promisify single api
promisify(wx.getSystemInfo)().then(console.log)
```

**Comment by kkzhilu** [comment]
很可惜哦，第一期推荐有一定的硬性Star要求，等后面几期再来试试吧~

**Comment by kkzhilu** [comment]
暂时关闭，后面几期可以考虑推荐
