### ISSUE TITLE
【自荐】有趣的在线聊天室

### ISSUE THREAD

**Issue by genalhuang** [juejin-im/open-source#3]
## 项目推荐
- 项目地址：https://github.com/genaller/genal-chat 

- 类别：typescript

- 项目后续更新计划：
  1. 加入用户标签
  2. 加入更多在线互动功能

- 项目描述：
  - 必写：聊天室项目,用来在线聊天,通过酷炫的界面和友好的交互提高用户聊天体验
  - 可选：初学者能够学到vue结合typescript的写法,nestjs的socket用法
  - 描述长度（不包含示例代码）:  本聊天室有着酷炫的界面和良好的代码规范,聊天室刷新数据持久化,刷新快速拿到所有数据和初始化socket成功,即时改名和改头像.

- 推荐理由：代码良好,界面有趣, 有利于新人学习,系统可扩展性良好

- 截图：（可选）gif/png/jpg
![genalChat](https://user-images.githubusercontent.com/46491653/88530760-72bbab80-d034-11ea-8b1f-97e6db352829.gif)

**Comment by kkzhilu** [comment]
这应该是一个绝佳的实践学习类开源项目，我们会在后期有专门的计划进行收录和推荐，再接再厉吧~
PS：第一期有硬性的star要求
