### ISSUE TITLE
【自荐】kafka一站式平台KafkaCenter

### ISSUE THREAD

**Issue by TrumanDu** [juejin-im/open-source#5]
## 项目推荐
- 项目地址：
https://github.com/xaecbd/KafkaCenter
- 类别：
Java

- 项目描述：
  - 必写：KafkaCenter是Kafka 集群管理和维护，生产/消费监控，生态组件使用的统一一站式平台。

- 推荐理由：令人眼前一亮的点是什么？解决了什么痛点？
  - **统一:** 一个平台，一站式包含自助，管理，监控，运维，使用一体化。
  - **流程化:** 创建topic流程化，做到对topic使用全生命周期管理。
  - **复用:** 平台支持接入多个集群，复用性很高。
  - **成本:** 只用部署一套程序，节省机器资源。降低运维成本，高效运维。
  - **生态:** 目前已经接入connect，ksql。
  - **便捷:** 提供便捷工具，让无需有kafka使用经验的人，都可以方便生产、消费消息。
  - **全局:** 可以站在不同的维度查看目前kafka使用情况
  - **权限:** 完善的权限设计，减少风险漏洞。

- 截图：
![](http://blogstatic.aibibang.com/screenshot.png)
![](http://blogstatic.aibibang.com/kafka-center.png)

**Comment by kkzhilu** [comment]
看起来很棒的项目，但是第一期暂时无法收录哦（第一期star有硬性要求）
小Tips：可以在掘金发沸点或者撰写开源文章给自己的项目增加热度呀🤞

另外，掘金马上要进行kafka的主题征文啦，乘着机会参加一波，让更多的人知道这个项目吧~

**Comment by SinowZ** [comment]
docker run -d -p 8088:8088 --name KafkaCenter -v ${PWD}/application.properties:/opt/app/kafkacenter/config/application.properties /xaecbd/kafka-center:2.2.0

想请教一下   ${PWD}这里怎么改呢?     假设我的application.properties在documents folder下.

**Comment by TrumanDu** [comment]
@SinowZ ${PWD}意思是你的当前目录即documents全路径

**Comment by SinowZ** [comment]
我不需要修改吗?   直接这样执行?

**Comment by TrumanDu** [comment]
@SinowZ windows可能不行，linux下可以

**Comment by SinowZ** [comment]
我用的mac,      可执行不成功,  提示我
docker: invalid reference format.
See 'docker run --help'.

**Comment by TrumanDu** [comment]
@SinowZ 那你把那个替换为你配置文件所在的全路径，不要换行

**Comment by SinowZ** [comment]
即使使用全路径也报上面这个错,  而且我也已经把路径加到docker file sharing里了.

**Comment by TrumanDu** [comment]
@SinowZ 你把你命令打出来。这个显示的是你docker命令格式错误

**Comment by SinowZ** [comment]
docker run -d -p 8088:8088 --name KafkaCenter -v /Users/xiuzhang/Documents/application.properties:/opt/app/kafkacenter/config/application.properties /xaecbd/kafka-center:2.2.0

**Comment by TrumanDu** [comment]
> docker run -d -p 8088:8088 --name KafkaCenter -v /Users/xiuzhang/Documents/application.properties:/opt/app/kafkacenter/config/application.properties /xaecbd/kafka-center:2.2.0
你这命令不对啊,多了一个`/`
```
docker run -d  -p 8080:8080 --name KafkaCenter -v ${PWD}/application.properties:/opt/app/kafkacenter/config/application.properties xaecbd/kafka-center:2.2.0
```

**Comment by TrumanDu** [comment]
@kkzhilu kafka征文推荐 [一站式Kafka平台KafkaCenter-开源啦](http://trumandu.github.io/2020/03/26/%E4%B8%80%E7%AB%99%E5%BC%8FKafka%E5%B9%B3%E5%8F%B0KafkaCenter-%E5%BC%80%E6%BA%90%E5%95%A6/)
