### ISSUE TITLE
【自荐】最全、最新的的 AndroidX Jetpack 相关组件的实践

### ISSUE THREAD

**Issue by hi-dhl** [juejin-im/open-source#6]
## 项目简介

* 项目地址：https://github.com/hi-dhl/AndroidX-Jetpack-Practice
* 语言：Kotlin
* 分类：Android
* 项目描述：
   
    本仓库致力于建立最全、最新的的 AndroidX Jetpack 相关组件的实践项目 以及组件对应的分析文章，目前已经包含的功能模块:
    
    * `AppStartupSimple` 是基于 Jetpack 成员 `App Startup` 开发的一个示例应用，从而提高了 App 的启动速度。
    * `Paging3SimpleWithDB` 是基于 Jetpack 成员 `Paging 3` 开发的加载本地数据库的示例应用
    * `Paging3SimpleWithNetWork` ： 是基于 Jetpack 成员 `Paging 3` 开发的加载网络数据的示例应用
    * `HiltSimple` ：是基于 Jetpack 成员 Hilt 开发的示例应用
    * `HiltWithAppStartupSimple` ： 是基于 Jetpack 成员 Hilt 开发的示例应用，结合了 `App Startup`、`ViewModel` 等等。
    * `HiltWithAppStartupSimple` ：是基于 Jetpack 成员 Hilt 在多模块中应用的示例
   
* 推荐理由:
  
    AndroidX-Jetpack-Practice 仓库里面的每个项目，使用的都是最新的技术，每个技术都有详细的文章分析其原理，如下所示：
   
    **AppStartupSimple**
    
    项目 `AppStartupSimple` 结构如下：
    
    * 模块 `ContentProvider`：提供了运行 `ContentProvider` 示例项目
    * 模块 `Startup-Library`：提供了运行 `App Startup` 示例项目
    
    关于 `AppStartupSimple` 分析的文章请看 [App Startup 实践以及原理分析](https://juejin.im/post/5ee4bbe4f265da76b559bdfe)

    **Paging3Simple**
    
    项目 Paging3Simple 涉及的技术栈：
    
    * 基于 kotlin 和 协程
    * 使用 koin 作为依赖注入库
    * JetPack
        * LiveData
        * Lifecycle
        * ViewModel
        * Room
        * Paging3
    * 架构
        * MVVM 架构
        * Repository 设计模式
        * Data Mapper 数据映射
    * 使用 Composing builds 作为依赖库的版本管理
    * JDataBinding 是基于 DataBinding 封装的库

    关于 `Paging3Simple` 加载本地数据分析的文章请看 [Jetpack 成员 Paging 3 实践以及原理分析（一）](https://juejin.im/post/5ee998e8e51d4573d65df02b)
    
    
    **Paging3SimpleWithNetWork**
    
    项目 Paging3SimpleWithNetWork 涉及的技术栈：

    * 基于 kotlin 和 协程
    * 使用 koin 作为依赖注入库
    * JetPack
        * LiveData
        * Lifecycle
        * ViewModel
        * Paging3
    * Retrofit 作为网络框架
    * 架构
        * MVVM 架构
        * Repository 设计模式
        * Data Mapper 数据映射
    * 使用 Composing builds 作为依赖库的版本管理
    * JDataBinding 是基于 DataBinding 封装的库
    
    关于 `Paging3SimpleWithNetWork` 加载网络数据分析的文章请看 [Jetpack 新成员 Paging3 网络实践及原理分析（二）](https://juejin.im/post/5eeefbf4e51d45742c53ddce)
    
    **HiltSimple**
    
    `HiltSimple` 是基于 Jetpack 成员 Hilt 开发的示例应用。

    * 项目包含了 Hilt 常用注解 `@HiltAndroidApp`、`@AndroidEntryPoint`、`@Inject`、`@Module`、`@InstallIn`、`@Provides`、`@EntryPoint` 等等的使用。
    * 还包含了 Hilt 如何和第三方库、Jetpack 其他成员的使用。
    
    关于 `HiltSimple` 项目分析的文章请查看 [Jetpack 新成员 Hilt 实践（一）启程过坑记](https://juejin.im/post/5ef2f31951882565a94e06a5)
    
    **HiltWithAppStartupSimple**
    
    `HiltWithAppStartupSimple` 包含了 Hilt 全部注解的使用案例，也包含了项目 `HiltSimple` 中用到案例，可以先去了解 `HiltSimple` 之后在来了解 `HiltWithAppStartupSimple` 会更加的清楚。
    
    关于 `HiltWithAppStartupSimple` 项目分析的文章请查看 [Jetpack 新成员 Hilt 实践之 App Startup（二）进阶篇](https://juejin.im/post/5ef7638c5188252e6a532db3)

    **HiltWithMultiModuleSimple**
    
    `HiltWithAppStartupSimple` 是基于 Jetpack 成员 Hilt 在多模块中应用的示例，项目中使用的注解都是前两篇文章介绍的内容。
    
    * [Jetpack 新成员 Hilt 实践（一）启程过坑记](https://juejin.im/post/5ef2f31951882565a94e06a5)
    * [Jetpack 新成员 Hilt 实践之 App Startup（二）进阶篇](https://juejin.im/post/5ef7638c5188252e6a532db3)
    
    关于 `HiltWithMultiModuleSimple` 项目分析的文章请查看 [Jetpack 新成员 Hilt 与 Dagger 大不同（三）落地篇](https://juejin.im/post/5efca0c1e51d4534a40d972f)

    **VersionPlugin**
    
    `VersionPlugin` 是基于 `Composing builds` 开发的自定义插件，作为整个仓库的依赖库的版本管理，使用 `Composing builds` 作为依赖库的版本管理，它有以下好处：
    
    * 编译速度快，升级单个依赖库，不需要更新整个项目
    * 支持 AndroidStudio 自动补全和单击跳转
    * ......
    
    关于 `VersionPlugin` 的分析的文章请看 [再见吧 buildSrc, 拥抱 Composing builds 提升 Android 编译速度](https://juejin.im/post/5ed3ef906fb9a047bf7070b6)。
    
    这是关于 buildSrc 和 Composing builds 详细使用案例的代码仓库的地址 [ComposingBuilds-vs-buildSrc](https://github.com/hi-dhl/ComposingBuilds-vs-buildSrc)，在代码中都要详细的注释。
    
* 项目后续更新计划：
    
    跟随 Google 最新的脚本，会第一时间添加最新的 Jetpack 实战项目，以及原理分析文章

E-mail: hihuilong@gmail.com

**Comment by kkzhilu** [comment]
这应该是一个绝佳的实践学习类开源项目，我们会在后期有专门的计划进行收录和推荐，再接再厉吧~
小Tips：可以在掘金发沸点或者撰写开源文章给自己的项目增加热度呀🤞
