### ISSUE TITLE
【自荐】Flutter Dojo—Flutter学习神器

### ISSUE THREAD

**Issue by xuyisheng** [juejin-im/open-source#7]
## 项目地址

[Flutter Dojo](https://github.com/xuyisheng/flutter_dojo)

## 特别之处

- 最全官方Widget详解
- 通过Pattern整合Flutter开发模式
- 不仅仅是UI，Flutter后端开发技巧也有
- 界面设计优美，讲解详细
- 通过App本身，了解Flutter开发的方方面面

### Widgets

Widgets部分的设计思路是为了演示Flutter中茫茫多的Widget的具体使用场景和功能，虽然只使用Flutter提供的一些基本Widget，已经可以实现大部分的界面、功能开发，但是，了解更多的Widget，可以让开发者的开发思路更广，使用更加合适的Widget来完成合适的开发场景。

经过迭代，Widgets部分已经完善了官方的所有Widget，以及官方在Category中未列举但是有很大实用价值的Widget。

### UI Pattern

UI Pattern部分的设计思路是为了帮助开发者了解如何使用Flutter来拆分大部分APP中的界面模板，通过Flutter实现一个个UI组件，来组合成完整的Flutter界面。

通过UI Pattern的学习，可以让开发者了解Flutter的具体解题思路，如何拆分UI的实现套路。

### Animations

Animations部分的设计思路是为了让开发者对Flutter的动画有一个完整的认识，针对不同的场景使用不同的动画方案，同时，对大部分常见的动画场景进行梳理，完成动画场景的归类。

### Back-end Util

Back-end Util这部分主要是针对Flutter中的非UI场景知识点进行的梳理，包括数据持久化、解析、状态管理等等。

### 搜索

全局强大的搜索功能，前后缀匹配，关键词搜索。

### 收藏

支持添加感兴趣的Widget到收藏夹。

## 解析文档

Welcome to the flutter_dojo wiki!

## 第一部分 总纲

[Flutter Dojo的设计之道](https://juejin.im/post/6854573219987341326)

## 第二部分

[Flutter Dojo设计之道——利用Github打造完善的开源项目](https://juejin.im/post/6856594295660085255)

[Flutter Dojo设计之道——骚气的闪屏动画是如何实现的](https://juejin.im/post/6857440683330895886)

[Flutter Dojo设计之道——如何打造一个通用的Playground](https://juejin.im/post/6858050410436001800)

未完待续。

**Comment by kkzhilu** [comment]
非常好的项目，但是暂时不接受具有一定引流性质的项目哦
如果你愿意把ReadMe中部分内容去掉，我们一定很乐意收录~

**Comment by xuyisheng** [comment]
已修改README，请查看~

**Comment by zisheng-ai** [comment]
@xuyisheng 正打算学学Flutter

**Comment by kkzhilu** [comment]
第一期我们主要考虑国内大厂的开源项目，已经打上【未来】标签，后续会纳入到对应专题，请持续关注吧~
