### ISSUE TITLE
【自荐】Redux-Model  ---  流畅的Redux模型，Typescript项目利器

### ISSUE THREAD

**Issue by fwh1990** [juejin-im/open-source#8]
https://github.com/redux-model/redux-model

用最少的代码，管理最多的数据，提供最多的类型提示。

**Comment by kkzhilu** [comment]
可以发现它的潜力很大，但是尚不能收录至项目中
小Tips：可以在掘金发沸点或者撰写开源文章给自己的项目增加热度呀🤞

**Comment by fwh1990** [comment]
收录的标准是什么呢？

**Comment by kkzhilu** [comment]
第一期有硬性的star要求哈
已经打了[未来]标签，我们会持续关注的
